# Phase 5.1: Simple TensorFlow Training Job
#
# A basic TFJob that trains a simple model
#
# Apply: kubectl apply -f 01_tfjob_simple.yaml
# Monitor: kubectl get tfjobs -n kubeflow-user-example-com
# Logs: kubectl logs -n kubeflow-user-example-com -l training.kubeflow.org/job-name=tf-simple -f
#
apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: tf-simple
  namespace: kubeflow-user-example-com
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: tensorflow
              image: tensorflow/tensorflow:2.13.0
              command:
                - "python"
                - "-c"
                - |
                  import tensorflow as tf
                  import numpy as np

                  print("=" * 50)
                  print("TensorFlow Simple Training Job")
                  print("=" * 50)
                  print(f"TensorFlow version: {tf.__version__}")
                  print(f"GPUs available: {len(tf.config.list_physical_devices('GPU'))}")

                  # Create simple model
                  model = tf.keras.Sequential([
                      tf.keras.layers.Dense(64, activation='relu', input_shape=(10,)),
                      tf.keras.layers.Dense(32, activation='relu'),
                      tf.keras.layers.Dense(1, activation='sigmoid')
                  ])

                  model.compile(
                      optimizer='adam',
                      loss='binary_crossentropy',
                      metrics=['accuracy']
                  )

                  print("\nModel Summary:")
                  model.summary()

                  # Generate synthetic data
                  np.random.seed(42)
                  X_train = np.random.randn(1000, 10)
                  y_train = (X_train[:, 0] + X_train[:, 1] > 0).astype(int)

                  X_test = np.random.randn(200, 10)
                  y_test = (X_test[:, 0] + X_test[:, 1] > 0).astype(int)

                  # Train
                  print("\nTraining...")
                  history = model.fit(
                      X_train, y_train,
                      validation_data=(X_test, y_test),
                      epochs=10,
                      batch_size=32,
                      verbose=1
                  )

                  # Evaluate
                  loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
                  print(f"\nFinal Results:")
                  print(f"  Loss: {loss:.4f}")
                  print(f"  Accuracy: {accuracy:.4f}")
                  print("=" * 50)
              resources:
                limits:
                  cpu: "2"
                  memory: "4Gi"
