apiVersion: v2
name: airflow-mlops
description: Wrapper chart for Airflow with MLOps infrastructure (PVC, etc.)
type: application
version: 1.0.0
appVersion: "3.0.2"

dependencies:
  - name: airflow
    version: "1.18.0"
    repository: "file://../airflow"
